name: Test markdown conversion

on:
  pull_request:
    paths:
      - checklist.md

permissions:
  contents: read

jobs:
  test_conversion_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: docker://pandoc/core:3.10.0.0
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --output=checklist.docx
            checklist.md
      - name: Upload converted document for preview
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: checklist.docx
          path: checklist.docx
