name: Convert markdown to Word
on: push

jobs:
  temp_conversion_via_pandoc:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.push.head.ref }}
      - name: run conversion
        run: |
          sudo apt-get install pandoc
          pandoc --standalone --output=checklist.docx checklist.md
      - uses: actions/upload-artifact@master
        with:
          name: checklist.docx
          path: checklist.docx
      - name: ⤴ Commit updated version
        run: |
          git config remote.origin.url 'https://${{secrets.GITHUB_TOKEN}}@github.com/potatoqualitee/froopyland-dr.git'
          git config user.name potatoqualitee
          git config user.email clemaire@gmail.com
          git add .
          git commit -am "update word"
          git push
