name: Convert markdown to Word
on: push

jobs:
  temp_conversion_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://pandoc/core:2.9
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --output=checklist.docx
            checklist.md
      - uses: actions/upload-artifact@master
        with:
          name: checklist.docx
          path: checklist.docx

  temp_commit_test:
    runs-on: ubuntu-latest
    steps:
      - name: commit if file changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: refreshing word doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
